-- hello-world 0001: create_notes
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS `p_hello_world_notes` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` varchar(255) NOT NULL,
  `text` text NOT NULL,
  `created_at` text NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
CREATE INDEX `idx_p_hello_world_notes_user_id` ON `p_hello_world_notes` (`user_id`);
