-- hello-world 0001: create_notes
-- Generated by termix-plugin migrations. Review before committing.

CREATE TABLE IF NOT EXISTS "p_hello_world_notes" (
  "id" integer PRIMARY KEY AUTOINCREMENT,
  "user_id" text NOT NULL,
  "text" text NOT NULL,
  "created_at" text NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_p_hello_world_notes_user_id" ON "p_hello_world_notes" ("user_id");
